-- MySQL Script generated by MySQL Workbench
-- Sat Aug 26 18:03:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classes` (
  `id` INT NOT NULL,
  `number_of_students` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teachers` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`classes_teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classes_teachers` (
  `id` INT NOT NULL,
  `classe_id` INT NULL DEFAULT NULL,
  `teacher_id` INT NULL DEFAULT NULL,
  INDEX `fk_teacher_id_idx` (`teacher_id` ASC) VISIBLE,
  INDEX `fk_class_id_idx` (`classe_id` ASC) VISIBLE,
  CONSTRAINT `fk_class_id1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `mydb`.`classes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_teacher_id`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`teachers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sessions` (
  `id` INT NOT NULL,
  `teachers_id` INT NOT NULL,
  `classes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `teachers_id`, `classes_id`),
  INDEX `fk_sessions_teachers1_idx` (`teachers_id` ASC) VISIBLE,
  INDEX `fk_sessions_classes1_idx` (`classes_id` ASC) VISIBLE,
  CONSTRAINT `fk_sessions_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `mydb`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sessions_classes1`
    FOREIGN KEY (`classes_id`)
    REFERENCES `mydb`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `id_class` INT NULL DEFAULT NULL,
  `sessions_id` INT NOT NULL,
  `sessions_teachers_id` INT NOT NULL,
  `sessions_classes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sessions_id`, `sessions_teachers_id`, `sessions_classes_id`),
  INDEX `fk_class_id_idx` (`id_class` ASC) VISIBLE,
  INDEX `fk_students_sessions1_idx` (`sessions_id` ASC, `sessions_teachers_id` ASC, `sessions_classes_id` ASC) VISIBLE,
  CONSTRAINT `fk_class_id`
    FOREIGN KEY (`id_class`)
    REFERENCES `mydb`.`classes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_students_sessions1`
    FOREIGN KEY (`sessions_id` , `sessions_teachers_id` , `sessions_classes_id`)
    REFERENCES `mydb`.`sessions` (`id` , `teachers_id` , `classes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`teachers_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teachers_students` (
  `id` INT NOT NULL,
  `teachers_id` INT NULL DEFAULT NULL,
  `student_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_teachers_id_idx` (`teachers_id` ASC) VISIBLE,
  INDEX `fk_student_id_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`students` (`id`),
  CONSTRAINT `fk_teachers_id`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `mydb`.`teachers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
